<?php

class Invalid_Name {}

class invalid_Name {}

class valid_name {}

class validname {}

class Invalid_name {}

class INVALID_Name {}

class INVALID_NAME {}

class INVALID_Name {}

class InValidName {}

class _Invalid_Name {}


interface Invalid_Name {}

interface invalid_Name {}

interface valid_name {}

interface validname {}

interface Invalid_name {}

interface INVALID_Name {}

interface INVALID_NAME {}

interface INVALID_Name {}

interface InValidName {}

interface _Invalid_Name {}

class ___ {}

interface ___ {}

class Invalid__Name {}

interface Invalid__Name {}

trait Invalid_Name {}

trait invalid_Name {}

trait valid_name {}

trait validname {}

trait Invalid_name {}

trait INVALID_Name {}

trait INVALID_NAME {}

trait INVALID_Name {}

trait InValidName {}

trait _Invalid_Name {}

trait ___ {}

trait Invalid__Name {}
